# Generated by Django 3.1.7 on 2021-03-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=500)),
                ('quanity', models.IntegerField()),
                ('lifetime', models.DateField()),
                ('bookingstatus', models.BooleanField()),
            ],
        ),
    ]
